package com.example.scannerkotlin.model

import java.time.LocalDateTime

data class ProductOffer(
    var iblockId: Int? = null,
    var catalogId: Int? = null,
    var name: String? = null,
    var active: String? = "Y",
    var code: String? = null,
    var xmlId: String? = null,
    var barcodeMulti: String? = "N",
    var canBuyZero: String? = "N",
    var createdBy: Int? = null,
    var modifiedBy: Int? = null,
    var dateActiveFrom: LocalDateTime? = null,
    var dateActiveTo: LocalDateTime? = null,
    var dateCreate: LocalDateTime? = null,
    var iblockSectionId: Int? = null,
    var iblockSection: List<Int>? = null,
    var measure: Int? = null,
    var previewText: String? = null,
    var detailText: String? = null,
    var previewPicture: Map<String, List<String>>? = null,
    var detailPicture: Map<String, List<String>>? = null,
    var previewTextType: String? = "text",
    var detailTextType: String? = "text",
    var sort: Int? = null,
    var subscribe: String? = "D",
    var vatId: Int? = null,
    var vatIncluded: String? = "N",
    var height: Double? = null,
    var length: Double? = null,
    var weight: Double? = null,
    var width: Double? = null,
    var quantityTrace: String? = "D",
    var purchasingCurrency: String? = null,
    var purchasingPrice: Double? = null,
    var quantity: Double? = null,
    var quantityReserved: Double? = null,
    var recurSchemeLength: Int? = 0,
    var recurSchemeType: String? = "D",
    var trialPriceId: Int? = null,
    var withoutOrder: String? = "N",
    var parentId: Int? = null,
    var properties: Map<String, Any>? = null
)